#==============================================#
  # Bomb Site by RedSMURF: Configuration file #
#==============================================#

[Main Settings]

SETTING_BOMB_LOAD       = 1       # Whether to load saved Bomb Site data of the current map
SETTING_BOMB_RADAR      = 1       # Whether to show the custom bomb sites location on the radar
SETTING_BOMB_ANYWHERE   = 1       # Whether to place bomb in all maps
SETTING_OFFSET_BASE     = 90.0    # Default forward offset when previewing Bomb Site placement
SETTING_OFFSET_MIN      = 42.0    # Minimum offset from the player to the Bomb Site
SETTING_OFFSET_MAX      = 900.0   # Maximum offset from the player to the Bomb Site
SETTING_OFFSET_STEP     = 10.0    # Step size when scrolling to move Bomb Site forward/backward
SETTING_OFFSET_FREQ     = 0.1     # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ      = 0.1     # Refresh rate of the ghost model (min = 0.1)
SETTING_SIZE_BASE       = 32.0
SETTING_SIZE_HEIGHT_MIN = 5.0
SETTING_SIZE_HEIGHT_MAX = 1500.0
SETTING_SIZE_WIDTH_MIN  = 5.0
SETTING_SIZE_WIDTH_MAX  = 1500.0

SETTING_ICON            = sprites/BombSite/bombTarget.spr
SETTING_ICON_SHOW       = 1
SETTING_ICON_SCALE      = 0.1
SETTING_ICON_ALPHA      = 90

SETTING_BEAM            = sprites/white.spr
SETTING_BEAM_COLOR      = 255 0 0