#==============================================#
  # Bomb Site by RedSMURF: Configuration file #
#==============================================#

[Main Settings]

SETTING_BOMB_LOAD       = 1       # Whether to load saved charger data of the current map
SETTING_BOMB_RADAR      = 1       # Whether to show the custom bomb sites location on the radar
SETTING_BOMB_DEFAULT    = 1       # Whether to delete the map's default bomb sites
SETTING_OFFSET_BASE     = 90.0    # Default forward offset when previewing charger placement
SETTING_OFFSET_MIN      = 42.0    # Minimum offset from the player to the charger
SETTING_OFFSET_MAX      = 900.0   # Maximum offset from the player to the charger
SETTING_OFFSET_STEP     = 10.0    # Step size when scrolling to move charger forward/backward
SETTING_OFFSET_FREQ     = 0.1     # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ      = 0.1     # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA     = 90      # Transparency level of the ghost preview model (0 - 255)
SETTING_SIZE_BASE       = 32.0
SETTING_SIZE_HEIGHT_MIN = 5.0
SETTING_SIZE_HEIGHT_MAX = 1500.0
SETTING_SIZE_WIDTH_MIN  = 5.0
SETTING_SIZE_WIDTH_MAX  = 1500.0

SETTING_BEAM             = sprites/white.spr